version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/ios"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10
    groups:
      ios-bundler:
        patterns:
          - "*"

  - package-ecosystem: "bundler"
    directory: "/android"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10
    groups:
      android-bundler:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10
    groups:
      pub:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
