version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/ios"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10

  - package-ecosystem: "bundler"
    directory: "/android"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10
