/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
// ignore_for_file: constant_identifier_names
// ignore_for_file: dangling_library_doc_comments

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData directions_walk = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atv = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baseball = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badminton = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bike = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bowling = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bow_arrow = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData billiards = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullseye_arrow = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxing_glove = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cricket = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_sports = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diving_scuba = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football_australian = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData curling = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fencing = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData golf = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horseshoe = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hiking = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handball = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData karate = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jump_rope = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paragliding = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mixed_martial_arts = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kettlebell = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kayaking = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData racquetball = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polo = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData roller_skate = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rollerblade = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sail_boat = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rugby = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rowing = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skate = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoe_ballet = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skateboard = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ski_water = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swim = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snowboard = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tennis = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table_tennis = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight_lifter = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volleyball = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yoga = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hockey_puck = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snowflake = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_polo = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diving_snorkel = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ski_water__1_ = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diving = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parachute = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carabiner = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horse_human = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData podium = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seesaw = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData run_fast = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unicycle = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bike_pedal = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_apple_outline = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode_scan = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
