// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:opennutritracker/core/data/data_source/custom_activity_template_dbo.dart';
import 'package:opennutritracker/core/data/data_source/user_activity_dbo.dart';
import 'package:opennutritracker/core/data/dbo/app_theme_dbo.dart';
import 'package:opennutritracker/core/data/dbo/calories_profile_dbo.dart';
import 'package:opennutritracker/core/data/dbo/config_dbo.dart';
import 'package:opennutritracker/core/data/dbo/fasting_session_dbo.dart';
import 'package:opennutritracker/core/data/dbo/intake_dbo.dart';
import 'package:opennutritracker/core/data/dbo/intake_type_dbo.dart';
import 'package:opennutritracker/core/data/dbo/meal_dbo.dart';
import 'package:opennutritracker/core/data/dbo/meal_nutriments_dbo.dart';
import 'package:opennutritracker/core/data/dbo/physical_activity_dbo.dart';
import 'package:opennutritracker/core/data/dbo/recipe_dbo.dart';
import 'package:opennutritracker/core/data/dbo/recipe_ingredient_dbo.dart';
import 'package:opennutritracker/core/data/dbo/tracked_day_dbo.dart';
import 'package:opennutritracker/core/data/dbo/user_dbo.dart';
import 'package:opennutritracker/core/data/dbo/user_gender_dbo.dart';
import 'package:opennutritracker/core/data/dbo/user_pal_dbo.dart';
import 'package:opennutritracker/core/data/dbo/user_weight_goal_dbo.dart';
import 'package:opennutritracker/core/data/dbo/water_intake_dbo.dart';
import 'package:opennutritracker/core/data/dbo/weight_log_dbo.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppThemeDBOAdapter());
    registerAdapter(CaloriesProfileDBOAdapter());
    registerAdapter(ConfigDBOAdapter());
    registerAdapter(CustomActivityTemplateDBOAdapter());
    registerAdapter(FastingSessionDBOAdapter());
    registerAdapter(IntakeDBOAdapter());
    registerAdapter(IntakeTypeDBOAdapter());
    registerAdapter(MealDBOAdapter());
    registerAdapter(MealNutrimentsDBOAdapter());
    registerAdapter(MealSourceDBOAdapter());
    registerAdapter(PhysicalActivityDBOAdapter());
    registerAdapter(PhysicalActivityTypeDBOAdapter());
    registerAdapter(RecipeDBOAdapter());
    registerAdapter(RecipeIngredientDBOAdapter());
    registerAdapter(TrackedDayDBOAdapter());
    registerAdapter(UserActivityDBOAdapter());
    registerAdapter(UserDBOAdapter());
    registerAdapter(UserGenderDBOAdapter());
    registerAdapter(UserPALDBOAdapter());
    registerAdapter(UserWeightGoalDBOAdapter());
    registerAdapter(WaterIntakeDBOAdapter());
    registerAdapter(WeightLogDBOAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppThemeDBOAdapter());
    registerAdapter(CaloriesProfileDBOAdapter());
    registerAdapter(ConfigDBOAdapter());
    registerAdapter(CustomActivityTemplateDBOAdapter());
    registerAdapter(FastingSessionDBOAdapter());
    registerAdapter(IntakeDBOAdapter());
    registerAdapter(IntakeTypeDBOAdapter());
    registerAdapter(MealDBOAdapter());
    registerAdapter(MealNutrimentsDBOAdapter());
    registerAdapter(MealSourceDBOAdapter());
    registerAdapter(PhysicalActivityDBOAdapter());
    registerAdapter(PhysicalActivityTypeDBOAdapter());
    registerAdapter(RecipeDBOAdapter());
    registerAdapter(RecipeIngredientDBOAdapter());
    registerAdapter(TrackedDayDBOAdapter());
    registerAdapter(UserActivityDBOAdapter());
    registerAdapter(UserDBOAdapter());
    registerAdapter(UserGenderDBOAdapter());
    registerAdapter(UserPALDBOAdapter());
    registerAdapter(UserWeightGoalDBOAdapter());
    registerAdapter(WaterIntakeDBOAdapter());
    registerAdapter(WeightLogDBOAdapter());
  }
}
